---
title: "Pre-Analysis Plan"
subtitle: "Drivers of Distributive Preferences: Symbolic Politics vs Self-Interest in Africa"
author: "Jennifer Hamilton & Ethan Christensen"
date: "May 11, 2018"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document:
    df_print: paged
header-includes:
- \usepackage{mathspec}
- \usepackage{amsmath,amsthm}
- \usepackage{dcolumn}
- \usepackage{framed}
- \usepackage[strings]{underscore}
- \usepackage{array}
---

\textit{Disclaimer}: The Afrobarometer website is technically experiencing technical difficulties, which we expect to be resolved in the near future. However, while we have been able to identify the text of the questions we would like to use, we have not been able to identify the standardized item number at present.

#Introduction

In his 1957 classic \textit{An Economic Theory of Democracy}, Anthony Downs adopts as a key assumption of his model that "cititzens act rationally in politics" [@downs_economic_1957 36]. That is, citizens cast votes aimed a maximizing their benefits from government. Downs allows that utility can be derived from altruistic action, not only from their material income or benefits. Nonetheless, research on voting behavior continues to conceptualize voting as a rational and/or self-intersted act. For instance, the oft-cited Meltzer-Richard model posits that voters take into account their position in the income distribution and vote to establish a system of taxation that maximizes their private material self-interest [@meltzer_rational_1981]. 

Mounting evidence suggests this idealized notion of a rational and materially self-interested voter is not representative of reality. Automatic emotional responses are now understood to play an important role in information processing and decision making. For instance, Charles S. Taber and Milton Lodge have collected evidence of "hot cognition," wherein political stimuli automatically and rapidly trigger an affective charge from long-term memory; these affective charges influence subsequent cognition [@lodge_automaticity_2005, @morris_activation_2003]. Such affectively charged cognitions falls short of the idealized rational cognition pervasive in political science models.

Recognizing the role of affect in preference formation, David Sears and coauthors developed a theory of symbolic politics [@sears_self-interest_1980, @sears_whites_1979, @lau_self-interest_1978]. Under this theory, citizens form predispositions toward political objects or symbols early in life that remain relatively stable over a lifetime. Later in life, exposure to stimulus reminiscent of that political symbol triggers an affectively charged response based on longstanding predispositions. The need for cognitive consistency outweights present material self-interest. As a result, "Political attitudes... are formed mainly in congruence with long-standing values about society and the polity, rather than short-term instrumentalities for satisfaction of one's current private needs" [@sears_self-interest_1980 671]. As a classic example, individuals most involed in anti-Vietnam war protest did not have much literal personal skin in game. They came from populations protected from the draft -- young women, as well as young men who received higher education exemptions from the draft. Symbolic predispositions better explain their actions than material self-interest.

In order to gain empirical traction on the theory, Sears and coauthors adopt a limited definition of self-interested attitudes as those that are "directed toward maximizing gains or minimizing losses to the individual's tangible private well-being," excluding other forms of utility such as value expression [@sears_whites_1979 369]. They chose measure of self-interest that are as fine-grained and  direct as possible. Measuring self-interest with demographic variables, for instance, is problematic because it fails to differentiate between current self-interest and pre-adult socialization. Using U.S. polling data, they found that symbolic predispositions (such as racial prejudice, nationalism, ideology, or party identification) explained far greater variation in attitudes toward the Vietnam war, unemployment policy, national health insurance, busing, and law and order than did material self-interest.

Our aim is to apply the symbolic politics theory to a new population. We will do so by leveraging World Values Survey and Afrobarometer questions that appopriately guage policy preference, symbolic predispositions, and material self-interest on four topics: immigration, privatization, education spending, and ebola prevention spending. We plan to investigate (1) whether symbolic predispositions and private material self-interest each have any explanatory potential over policy preferences, and (2) whether symbolic predispositions has greater explanatory potential than material self-interest. 

Owing to the difficult of manipulating either symbolic predispositions or material self-interest, our investigation will not be causally identified. Nonetheless, we believe this project could make several important contributions to the literature:

\begin{itemize}
  \item To our knowledge, the theory of symbolic politics has not been applied outside the United States. Applying the theory in sub-Saharan Africa presents a new test for the theory in a new context. In particular, mayn psychological theories have not been adequately tested in non-WEIRD, i.e. non-Western, educated, industrialized, rich, democratic, societies [henrich_weirdest_2010].
  \item Should symbolic politics prove resilient to this new context, the findings will allow better insight as to why ethnicity remains salient in African politics. Recent findings suggest that ethnic favoritism may not be as pervasive as once thought [@kasara_tax_2007, @kramon_who_2013, @burgess_value_2015]. Nonetheless, if ethnic group identity is a powerful symbolic attitude, political mobilization along ethnic lines may persist even where ethnic bias in service provision has faded. In addition, it may lead us to question models that assume rational voter behavior. For instance, the recent Metaketa I supposed that information on government performance would alter voter behavior. Expectations of such self-interested behavior may be misinformed if symbolic politics dominate voter preferences.
  \item Should symbolic politics not prove resilient in this new context, this finding will also be relevant to discussions over the salience of ethnic identity in African politics.
\end{itemize}

# Description of data

In this study we plan to utilize data from the World Values Survey and Afrobarometer surveys. The World Values Survey (WVS) is the largest and longest-running non-commercial cross-national survey of beliefs and values. The most recently completed wave surveyed participants from almost 100 countries in 2011-2014. Each country-level survey has a minimum of 1,200 respondents (ages 18-85), conducted through face-to-face interviews. Depending on the country, sampling occurs through either probability or a combination of probability and stratified random sampling as noted in the documentation. From these countries, we identify the five that are in sub-Saharan Africa: Ghana, Nigeria, Rwanda, South Africa, and South Africa.

Afrobarometer is a long running survey designed specifically to understand political attitudes and behaviors in sub-Saharan Africa. Respondents answer questions on a variety of topics including public services, governance, identity, and political participation. There have been six completed waves, with the most recent in 2015/2016 also covering the most countries (36). Most country surveys have either 1,200 or 2,400 respondents. Each survey uses a clustered, stratified, multi-stage, area probability sample. Occasionally a survey will oversample a politically relevant sub-population in order to ensure a large-enough subsample.

From these two sources we identify the four policy preference choices available to us as listed above. For each topic we use different samples of countries based on the data available. The relevant questions on immigration and privatization are contained in the WVS and so is limited to those five countries. The relevant data on Ebola from the Afrobarometer surveys in Liberia and Guinea. We subset our analysis of education preferences to countries where there appears to be no ethnic preference in education outcomes. If ethnic preferences exist, then symbolic politics and self-interest point in the same direction and are difficult to disentangle. We select this subset using Franck and Rainer's results on ethnic preferences [-@franck_does_2012]. We limit our analysis to only countries in which no more than one of their four indicators have statistical significance. This leaves us with data from eight countries.

####On inclusion of Ebola spending question

In early stages of this project, concerns were cited regarding general Ebola knowledge and the prevalence of Ebola mythology in Liberia and Sierra Leone. If respondents lacked knowledge of Ebola, they might not be able to appropriately assess their own self interest and the consequences of the policies they advocate. We believe this should not be a concern. Mythology and knowledge gaps were common at the outbreak of the Ebola epidemic in 2013. However, Afrobarometer's Round 6 survey was not administered in Liberia and Sierra Leone until 2015, well after a series of public information campaigns aimed at improving knowledge and dispelling myths began. We believe there is sufficient evidence of sufficient Ebola knowledge for participants to answer the survey questions posed [@kobayashi_community_2015, @jiang_rapid_2016, @wilken_knowledge_2017].

#Hypotheses

Based on the original findings of the Sears and coauthors' papers, we expect that both symbolic attitudes and self-interest will be jointly significant in the model for each question considered. Generally speaking, we expect that symbolic attitudes go further to explain policy preferences than do self-interest. 

However, we expect the opposite in the case of Ebola spending. Sears and coauthors hypothesized that self-interest will outweigh symbolic politics when policy consequences are particularly "definite, concrete, and immediate," citing several examples [-@sears_self-interest_1980 680]. Recent and traumatic personal experiences with Ebola likely fit this mold.

#Variable construction

For all items, "party in power" will mean party in control of the executive.

\textit{Note: we still have not yet decided how we will treat "don't know" or "not applicable" responses. We will determine this before finalizing our PAP.}

##Immigration 

\textit{Source}: World Values Survey Round 6 

\textit{Policy preference question}: (V46) When jobs are scarce, employers should give priority to people of this country over immigrants. 

\textit{Scaling}: Agree (1), neither (0.5) or disagree (0)

**Symbolic Attitudes Items**

\begin{enumerate}
  \item (V101) Wealth accumulation ideology \textit{Scaling}: People can only get rich at the expense of others (1) to Wealth can grow so there´s enough for everyone (10).  \textit{Expected sign}: negative.
  \item (V96) Income inequality ideology. \textit{Scaling}: Incomes should be made more equal (1) to We need larger income differences as incentives for individual effort (10). \textit{Expected sign}: negative.
  \item (V211) How proud of nationality. \textit{Scaling}: (1) Very proud, quite proud, not very proud, not very proud at all (0). \textit{Expected sign}: positive. 
  \item (V107) How much you trust: People of another nationality. \textit{Scaling}: (1) trust completely, trust somewhat, do not trust very much, do not trust at all (0).\textit{Expected sign}: negative.
  \item (V214) I see myself as part of the [country] nation. \textit{Scaling}: (1) strongly agree, agree, disagree, strongly disagree (0). \textit{Expected sign}: negative.
  \item (V29) Party preference. \textit{Scaling}: Recode 1 for part in power, else 0. \textit{Expected sign}: unclear.
  \item (V16) Important child qualities: tolerance and respect for other people. \textit{Scaling}: mentioned (1) or not mentioned (0). \textit{Expected sign}: negative.
  \item (V95) Self-positioning on political scale. \textit{Scaling}: Left (1) to Right (10). \textit{Expected sign}: negative.
  \item (V98) Government responsibility. \textit{Scaling}: Government should take more responsiboity to ensure that everone is provided for (1) to People should take more responsibility to provide for themselves (10). \textit{Expected sign}: negative.
\end{enumerate}

**Self-Interest Items**

\begin{enumerate}
  \item (V243) Mother is an immigrant. \textit{Scaling}: yes (1), no (0) \textit{Expected sign}: positive 
  \item (V244) Father is an immigrant. \textit{Scaling}: yes (1), no (0) \textit{Expected sign}: positive 
  \item (V245) Respondent is an immigrant. \textit{Scaling}: yes (1), no (0). \textit{Expected sign}: positive.
  \item (V191) In the past 12 months, gone without case income. \textit{Scaling}: (1) often, sometimes, rarely, never (0). \textit{Expected sign}: positive.
  \item (V229) Employment status. \textit{Scaling}: 1 for unemployed, else 0. \textit{Expected sign}: positive.
  \item (V236) Is the chief wage earner employed now or not, \textit{Scaling}: yes (0), no (1). \textit{Expected sign}:positive.
  \item (V59) Satisfaction with financial situation of household. \textit{Scaling}: (1) completely dissatisfied to (10) completely satisfied. \textit{Expected sign}: negative.
  \item (V181) Worries: Losing my job or not finding a job. \textit{Scaling}: (1) very much, a great deal, not much, not much at all (0). \textit{Expected sign}: positive.
\end{enumerate}

##Privatization 

\textit{Source}: World Values Survey Round 6 

\textit{Policy preference question}: (V97) Private vs. state ownership of business

\textit{Scaling}: Private ownership of business and industry should be increased (1) to Government ownership of business and industry should be increased (10).

**Symbolic Attitudes Items**

\begin{enumerate}
  \item (V96) Income inequality ideology. \textit{Scaling}: Incomes should be made more equal (1) to We need larger income differences as incentives for individual effort (10). \textit{Expected sign}: negative.
  \item (V29) Party preference. \textit{Scaling}: Recode 1 for part in power, else 0. \textit{Expected sign}: unclear.
  \item (V95) Self-positioning on political scale. \textit{Scaling}: Left (1) to Right (10). \textit{Expected sign}: negative.
  \item (V98) Government responsibility. \textit{Scaling}: Government should take more responsiboity to ensure that everone is provided for (1) to People should take more responsibility to provide for themselves (10). \textit{Expected sign}: negative.
\end{enumerate}

**Self-interest Items **

\begin{enumerate}
 \item (V230) Sector of employment \textit{Scaling}: government or public institution (1), else 0.
\end{enumerate}

##School fees 

\textit{Source}: Afrobarometer Round 3

\textit{Policy preference question}: Which of the following statements is closest to your view?. Choose Statement A or Statement B. A: It is better to have free schooling for our children, even if the quality of education is low. B: It is better to raise educational standards, even if we have to pay school fees.

\textit{Scaling}: Strongly agree with A (1) to Strongly agree with B (0)

**Symbolic Attitudes Items**

\begin{enumerate}
  \item Think about the condition of [respondent’s identity group]. Do they have less, the same, or more influence in politics than other groups in this country? \textit{Scaling}: (1) much more, more, same, less, much less (0).  \textit{Expected sign}: positive.
  \item How often are [respondent’s identity group] treated unfairly by the government? \textit{Scaling}: (1) never, sometimes, often, always (0).  \textit{Expected sign}: positive.
  \item Let us suppose that you had to choose between being a [nationality] and being a [respondent’s identity group]. Which of the following statements best expresses your feelings? \textit{Scaling}: (1) ethnic ID only, ethnic ID more, national and ethnic, national ID more, national ID only (0).  \textit{Expected sign}: negative.
  \item How much do you trust each of the following types of people: [countrywomen] from other ethnic groups? \textit{Scaling}: (1) Not at all, just a little, somewhat, a lot (0).  \textit{Expected sign}: negative.
  \item Let’s talk for a moment about the kind of society we would like to have in this country. Which of the following statements is closest to your view?. Choose Statement A or Statement B. A: People should look after themselves and be responsible for their own success in life. B: The government should bear the main responsibility for the well-being of people. \textit{Scaling}: strongly agree with A (1) to strongly agree with B (0).  \textit{Expected sign}: negative.
  \item Close to which party \textit{Scaling}: recode 1 for party in power, else.  0. \textit{Expected sign}: positive.
\end{enumerate}

**Self-interest Items**

\begin{enumerate}
  \item Over the past year, how often, if ever, have you or your family gone without: School expenses for your children (like fees, uniforms or books)? \textit{Scaling}: (1) never, just once or twice, several times, many times, always (0). \textit{Expected sign}: negative.
  \item Have you encountered any of these problems with your local public schools during the past 12 months?. Services are too expensive / Unable to pay. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: negative.
  \item Have you encountered any of these problems with your local public schools during the past 12 months?. Lack of textbooks or other supplies. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: positive.
  \item Have you encountered any of these problems with your local public schools during the past 12 months?. Poor teaching. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: positive.
  \item Have you encountered any of these problems with your local public schools during the past 12 months? Absent teachers. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: positive.
  \item Have you encountered any of these problems with your local public schools during the past 12 months?. Overcrowded classrooms. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: positive.
  \item Have you encountered any of these problems with your local public schools during the past 12 months? Poor conditions of facilities. \textit{Scaling}: (1) never, once or twice, several times, many times, always (0). \textit{Expected sign}: positive.
\end{enumerate}

##Ebola spending 

\textit{Source}: Afrobarometer Round 6 

\textit{Policy preference question}: (Q86g-Lib/Q86g-SRL) Statement 1: Government should devote more resources to Ebola vs Statement 2: focus on other problems. 

\textit{Scaling}: Agree very strongly with 1 (1) to agree very strongly with 2 (0)

**Symbolic Attitudes Items**

\begin{enumerate}
  \item Attitudes toward Westerners: identify U.S. or former colonial power as model country for development. \textit{Scaling}: recoded from open-ended question, 1 for U.S. or former colonial power, 0 otherwise. \textit{Expected sign}: negative.
  \item How often are [respondent’s identity group] treated unfairly by the government? \textit{Scaling}: (1) never, sometimes, often, always (0).  \textit{Expected sign}: positive.
  \item Let us suppose that you had to choose between being a [nationality] and being a [respondent’s identity group]. Which of the following statements best expresses your feelings? \textit{Scaling}: (1) ethnic ID only, ethnic ID more, national and ethnic, national ID more, national ID only (0).  \textit{Expected sign}: negative.
  \item Close to which party \textit{Scaling}: recode 1 for party in power, else.  0. \textit{Expected sign}: positive.
  \item 
\end{enumerate}

**Self-Interest Items**

\begin{enumerate}
  \item (Q83a-Lib/Q83a-SRL) Know close friend or relative who was infected with Ebola. \textit{Scaling}: yes (1), no (0). \textit{Expected sign}: positive.
  \item (Q84a-Lib/Q84a-SRL) Unable to attend school due to Ebola. \textit{Scaling}: (1) never, just once or twice, several times, many times (0). \textit{Expected sign}: positive.
  \item (Q84b-Lib/Q84b-SRL) Unable to work due to Ebola. \textit{Scaling}: (1) never, just once or twice, several times, many times (0). \textit{Expected sign}: positive.
  \item (Q84c-Lib/Q84c-SRL) Unable to attend social gatherings due to Ebola. \textit{Scaling}: (1) never, just once or twice, several times, many times (0). \textit{Expected sign}: positive.
  \item (Q84d-Lib/Q84d-SRL) Unable to get medical care for other health problems due to Ebola. \textit{Scaling}: (1) never, just once or twice, several times, many times (0). \textit{Expected sign}: negative.
\end{enumerate}


#Model

\textit{Note: We are still deciding which model would be most appropriate, as response variables are not binary but they are bounded from 0 to 1. Logit might be better? We will determine this before finalizing our PAP.}

For each policy area, we will run an OLS regression with policy preference as the dependent variable and with symbolic attitudes and self-interest indices as the independent variables. We will also control for demographic variables including gender, age, education, and ethnicity. Thus, the model will take the form:

\begin{equation}
y_i = \beta_0 + \textbf{X}_{i1}\beta_1 + \textbf{X}_{i2}\beta_2 +  \textbf{X}_{i3}\beta_3 + \epsilon_i 
\end{equation}

where:

\begin{itemize}
  \item $\textbf{X}_{i1}$ represents a matrix of symbolic attitudes indicators and $\beta_1$ represents a vector of coefficients for each symbolic attitude indicator.
  \item $\textbf{X}_{i2}$ represents a matrix of self-interest indicators and $\beta_2$ represents a vector of coefficients for each self-interest indicator.
  \item $\textbf{X}_{i3}$ represents a matrix of control variables and $\beta_3$ represents a vector of coefficients for each control variable.
\end{itemize}

Note that symbolic attitudes and self-interest are thus *not* summary indices; rather, each indictor is entered individually into the model. This replicates the original methodology used in Sears and coauthors' series of symbolic politics papers [@sears_whites_1979, @sears_self-interest_1980]. 

#Hypothesis tests

For each model, we will conduct the following hypothesis tests:

##Joint F tests

To test whether symbolic attitudes and material self-interest each contribute to the formation of policy preferences, we will use joint F-tests. These test are NOT drawn from the Sears and coauthors papers, which only consider the statistical significance of each covariate individually.

####Symbolic Attitudes

Recalling that $\beta_1$ is a vector of coefficients on all symbolic attitude covariates, the F-test for joint significance of symbolic attitudes indicators has the following hypotheses:

$$\begin{aligned}
H_0 \  &: \beta_1 = \textbf{0}\\ H_A&: \beta_1 \neq \textbf{0}
\end{aligned}$$

Hence, the restricted model will be

\begin{equation}
y_i = \beta_0 + \textbf{X}_{i2}\beta_2 +  \textbf{X}_{i3}\beta_3 + \epsilon_i
\end{equation}

####Self-interest

Recalling that $\beta_2$ is a vector of coefficients on all self-interest covariates, the F-test for joint significance of self-interest indicators has the following hypotheses:

$$\begin{aligned}
H_0\ &: \beta_2 = \textbf{0}\\ H_A &: \beta_2 \neq \textbf{0}
\end{aligned}$$

Hence, the restricted model will be 

\begin{equation}
y_i = \beta_0 + \textbf{X}_{i1}\beta_1 +  \textbf{X}_{i3}\beta_3 + \epsilon_i
\end{equation}

####Standard errors

For both joint F-test, we will use cluster-robust standard errors, with primary sampling units as the cluster.

##R-squared comparison test

In the original Sears and coauthors analysis compared the relative contribution of symbolic attitudes and self-interest to policy preferences by comparing the $R^2$ contribution made by each set of covariates. For instance, the contribution of symbolic attitudes will be:

$$R^2_{\text{symbolic}} = R^2_1 - R^2_2$$

where 

\begin{itemize}
  \item $R^2_{\text{symbolic}}$ represents the explanatory contribution of symbolic attitudes.
  \item $R^2_1$ represents the coefficent of determination for the full model, including symbolic attitude indicators, self-interest indicators, and control variables (equation 1).
  \item $R^2_2$ represents the coefficient of determination for the restricted model which excludes symbolic attitude indicators, but includes both self-interest indicators and control variables (equation 2).
\end{itemize}

Using the same technique, the contribution of self-interest will be:

$$R^2_{\text{self-interest}} = R^2_1 - R^2_3$$

where 

\begin{itemize}
  \item $R^2_{\text{self-interest}}$ represents the explanatory contribution of self interest.
  \item $R^2_1$ represents the coefficent of determination for the full model, including symbolic attitude indicators, self-interest indicators, and control variables (equation 1).
  \item $R^2_2$ represents the coefficient of determination for the restricted model which excludes self-interest indicators, but includes both symbolic attitudes indicators and control variables (equation 2).
\end{itemize}

We will also use these estimates. However, we will extend the original analysis by estimating the standard errors of the $R^2$ contributions using bootstrapping, enabling us to assess more rigorously whether contribution of either symbolic attitudes or self-interest clearly outweights the other. Thus, we will test the following hypotheses:

$$\begin{aligned}
H_0 \ &: R^2_{\text{symbolic}} - R^2_{\text{self-interest}} = 0\\ H_A&: R^2_{\text{symbolic}} - R^2_{\text{self-interest}} \neq 0
\end{aligned}$$

We will conduct 10,000 bootstraps to estimate standard errors. Our goal is to maintain consistency between the original sampling procedure and our bootstrap resampling method. However, we face certain practical limitations.

\textit{Disclaimer: We are not yet settled on our bootstrapping procedure and will seek further advice before finalizing our PAP.}

Afrobarometer uses consistent sampling policies across countries and across survey rounds. For Afrobaromter questions, we will (1) divide the data back into country samples, (2) stratify the data by urban and rural PSUs within each country, and (3) resample PSUs within each strata. The World Values Survey does not use consistent sampling methods across countries. As such, we resample according to the lowest common denominator among country sampling procedures (1) divide the data back into country samples, and (2) resample PSUs within each country.

##Sub-group analyses

In their 1980 paper, Sears and coathors also examine results from a series of sub-group analyses on the premise that self-interest may be more prominent in preference formation under certain circumstances. i.e. within certain groups. They developed indices for political sophistication, private-regarding values, perceived government responsiveness, sense of political efficacy, and perceiving the issue as a very important problem. 

\textit{Looking for feedback: Should we subset within each country and then re-aggregate, or should we simply sub-set the merged data?}

####Political Sophistication

This subgroup analysis is of greatest importance for Sears and coauthors, as rationally self-interested behavior presumes the availability of adequate information. In their 1980 analysis, they measure political sophistication using a composite index of education, basic political knowledge, self-reported interest in the ongoing political campaign, and the number of media in which the campaign was followed [@sears_self-interest_1980]. Following the discussion of political sophistication measures by John Zaller [@zaller_nature_1992], we do not replicate Sears and coauthors' composite index and instead use a summary index based solely on political knowledge. These data are available for the Afrobarometer question from Round 3 only (preference on school fees), so this is the only policy on which we complete this sub-group analysis.

To measure political sophistication, we use an additive index based on the following questions:

\begin{itemize}
  \item Can you tell me the name of: Your deputy name at the National Assembly?
  \item Can you tell me the name of: Your local government councilor?
  \item Can you tell me the name of: Your Deputy President?
  \item Do you happen to know which is the political party with the most seats at the National Assembly?
  \item Do you happen to know how many times a person can be elected president?
  \item Do you happen to know who is responsible of determining if a law is constitutional or not?
\end{itemize}

Please note that Afrobarometer questionnaires for individual countries are customized to include appropriate terms for each country (e.g. MP versus deputy). We code 1 for the correct response, as identified by Afrobarometer enumerators, and 0 for all other responses (including "know but can't remember").

Like Sears and coauthors [-@sears_self-interest_1980], we will split the participant pool at the median and rerun the tests separately on each half (below median and above median). 

####Private-regarding values

The World Values Survey contains questions that will allow us to measure private-regarding values. We assess private-regarding using Schwartz values questions which describe traits of a hypothetical person and ask the respondent how similar they believe they are to the hypothetical. We will create an additive index based on the following questions, with responses to each question normalized on a scale from 0 to 1.

\begin{itemize}
  \item (V70) It is important to this person to think up new ideas and be creative; to do things one’s own way. Response options: (1) very much like me, like me, somewhat like me, a little like me, not like me, not like me at all (0)
  \item (V71) It is important to this person to be rich; to have a lot of money and expensive things. Response options: (1) very much like me, like me, somewhat like me, a little like me, not like me, not like me at all (0)
  \item (V74) It is important to this person to do something for the good of society. Response options: (0) very much like me, like me, somewhat like me, a little like me, not like me, not like me at all (1)
  \item (V75) It is important to help people living nearby; to care for their needs. Response options: (0) very much like me, like me, somewhat like me, a little like me, not like me, not like me at all (1)
\end{itemize}

We will split the sample at the median, rerunning our analysis separately on each half.

\textit{Again, should we split within each country or within the merged sample?}

####Perceived government responsiveness

Afrobarometer Round 3 contains several questions which allow us to measure perceived government responsiveness, allowing us to subset our data for policy preferences on school fees. We will create an additive index based on the following questions, with responses to each question normalized on a scale from 0 to 1.

\begin{itemize}
  \item How much of the time do think the following try their best to listen to what people like you have to say: Members of Parliament? Response options: (0) never, only sometimes, often, always (1)
  \item How much of the time do think the following try their best to listen to what people like you have to say: Local Government Councillors? Response options: (0) never, only sometimes, often, always (1)
  \item Taking the Problem you mentioned first [as the highest prioirity problem facing the country], how likely is it that the government will solve your most important problem within the next few years? Reponse options: (0) not at all likely, likely, not very likely, likely, very likely (1)
\end{itemize}

We will split the sample at the median, rerunning our analysis separately on each half.

\textit{Again, should we split within each country or within the merged sample?}


####Sense of political efficacy

Afrobarometer Round 3 contains a question on political efficacy, allowing us to conduct this sub-group analysis for question. This question reads: "Do you agree or disagree with the following statements? Politics and government sometimes seem so complicated that you can’t really understand what’s going on." We divide respondents into those who agree (includes both agree and strongly agree) and those who disagree (both disagree and strongly disagree), dropping those who respond with "neither agree or disagree" or "don't know". We replicate our analysis on each sub-group.

####Issue importance

In both rounds of Afrobarometer that we use, respondents were asked to identify up to the three most important problems facing the country that the government should address. For our school fees question from Afrobarometer Round 3, we will divide respondents into those who identified education as an important problem (regardless of whether first, second, or third choice) and those who did not, rerunning our tests on each subset. 

% For our healthcare question from Afrobarometer Round 6, we will divide respondents into those who identified health or sickness/disease as an important problem (again, regardless or order stated) and those who did not, rerunning our tests on each subset. Note that we do not include those who identify AIDS as a priority in the former group, as we found this response more ambiguous vis-a-vis the healthcare system: addressing AIDS may involve better healthcare provisions (relevant to the policy preference question), but alternatively may mean addressing social stigma (not directly relevant to the policy preference question).

%Round 6: priorities for investment? (Healthcare)

#Multiple hypothesis testing

We will use the Benjamimi-Hochberg Procedure to address false discovery through multiple hypothesis testing. In other words, we will:

\begin{itemize}
  \item Order the p-values for each of $m$ hypothesis tests such that $p_1 \leq p_2 \leq \ldots \leq p_m$.
  \item Maximize $k$ such that $p_i \leq \frac{\alpha \cdot k}{m}$. This value will be $k^*$.
  \item Reject all hypotheses $H_k$ for $k \leq k^*$
\end{itemize}